## Γιατί λίστες

1. Μπορούν να περιέχουν διαφορετικά είδη δεδομένων (αριθμούς, χαρακτήρες κτλ)
2. Το μέγεθός τους είναι δυναμικό

## Γιατί όχι λίστες

1. Λόγω των παραπάνω, καταναλώνουν πολύ μνήμη
2. Δεν μπορούν να αντεπεξέλθουν σε μεγάλα σύνολα δεδομένων

In [1]:
import numpy as np
vector = np.array([10, 20, 30])
print(vector)

[10 20 30]


Χωρίς την print() η μορφή είναι ως

In [2]:
vector

array([10, 20, 30])

In [3]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### shape

Μπορούμε εύκολα να βρούμε το μέγεθος ενός ndarray με τη χρήση της shape

In [4]:
vector.shape

(3,)

In [5]:
matrix.shape

(3, 3)

In [6]:
births = np.genfromtxt("births.csv", delimiter=",")

In [7]:
print(births)

[[             nan              nan              nan              nan
               nan]
 [  1.99400000e+03   1.00000000e+00   1.00000000e+00   6.00000000e+00
    8.09600000e+03]
 [  1.99400000e+03   1.00000000e+00   2.00000000e+00   7.00000000e+00
    7.77200000e+03]
 ..., 
 [  2.00300000e+03   1.20000000e+01   2.90000000e+01   1.00000000e+00
    1.28230000e+04]
 [  2.00300000e+03   1.20000000e+01   3.00000000e+01   2.00000000e+00
    1.44380000e+04]
 [  2.00300000e+03   1.20000000e+01   3.10000000e+01   3.00000000e+00
    1.23740000e+04]]


In [8]:
births = np.genfromtxt("births.csv", delimiter=",", skip_header=1, dtype =np.int16)
print(births)

[[ 1994     1     1     6  8096]
 [ 1994     1     2     7  7772]
 [ 1994     1     3     1 10142]
 ..., 
 [ 2003    12    29     1 12823]
 [ 2003    12    30     2 14438]
 [ 2003    12    31     3 12374]]


In [9]:
# 0 γραμμή, 3η στήλη
births[0,3]

6

In [10]:
# όλες οι γραμμές, 3η στήλη
births[:,3]

array([6, 7, 1, ..., 1, 2, 3], dtype=int16)

In [11]:
# 2η γραμμή, όλες οι στήλες
births[2,:]

array([ 1994,     1,     3,     1, 10142], dtype=int16)

In [12]:
first_two_columns = births[:,0:2]
print(first_two_columns)

[[1994    1]
 [1994    1]
 [1994    1]
 ..., 
 [2003   12]
 [2003   12]
 [2003   12]]


In [13]:
first_ten_rows = births[0:10,:]
print(first_ten_rows)

[[ 1994     1     1     6  8096]
 [ 1994     1     2     7  7772]
 [ 1994     1     3     1 10142]
 [ 1994     1     4     2 11248]
 [ 1994     1     5     3 11053]
 [ 1994     1     6     4 11406]
 [ 1994     1     7     5 11251]
 [ 1994     1     8     6  8653]
 [ 1994     1     9     7  7910]
 [ 1994     1    10     1 10498]]


## Αντικατάσταση τιμών

In [14]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45] ])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
matrix[0,:] = 10
matrix

array([[10, 10, 10],
       [20, 25, 30],
       [35, 40, 45]])

### Αναζήτηση  σε ndarray

In [16]:
vector = np.array([5, 10, 15, 20])
greater_to_ten = (vector > 10)

print(greater_to_ten)

[False False  True  True]


In [17]:
vector[greater_to_ten]

array([15, 20])

In [18]:
year_is_1994 = births[:,0] == 1994
year_is_1994

array([ True,  True,  True, ..., False, False, False], dtype=bool)

In [19]:
year_1994 = births[year_is_1994,:]
print(year_1994)

[[ 1994     1     1     6  8096]
 [ 1994     1     2     7  7772]
 [ 1994     1     3     1 10142]
 ..., 
 [ 1994    12    29     4 12189]
 [ 1994    12    30     5 12051]
 [ 1994    12    31     6  8809]]


In [20]:
month_is_10_first = (births[:,1] == 10) & (births[:,2] == 1)
month_10 = births[month_is_10_first,:]
print(month_10)

[[ 1994    10     1     6  9351]
 [ 1995    10     1     7  8545]
 [ 1996    10     1     2 12851]
 [ 1997    10     1     3 12161]
 [ 1998    10     1     4 12410]
 [ 1999    10     1     5 12544]
 [ 2000    10     1     7  8279]
 [ 2001    10     1     1 12109]
 [ 2002    10     1     2 13296]
 [ 2003    10     1     3 13138]]


In [21]:
year_is_1994 = births[:,0] == 1994
births[:,0][year_is_1994] = 2020
print(births)

[[ 2020     1     1     6  8096]
 [ 2020     1     2     7  7772]
 [ 2020     1     3     1 10142]
 ..., 
 [ 2003    12    29     1 12823]
 [ 2003    12    30     2 14438]
 [ 2003    12    31     3 12374]]


## Πράξεις σε ndarray

In [22]:
vector = np.array([5, 10, 15, 20])

In [23]:
vector*3

array([15, 30, 45, 60])

Παρατηρούμε ότι το αρχικό μας διάνυσμα δεν άλλαξε. Οπότε αν θέλουμε να το αντικαταστήσουμε, θα πρέπει να το θέσουμε ξανά

In [24]:
vector

array([ 5, 10, 15, 20])

In [25]:
vector = vector*3
vector

array([15, 30, 45, 60])

In [26]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [27]:
matrix[:,0] = matrix[:,0]*2

In [28]:
matrix

array([[10, 10, 15],
       [40, 25, 30],
       [70, 40, 45]])

In [29]:
vector.sum()

150

Βάζοντας την παράμετρο axis στο sum, μπορούμε να πάρουμε για 1 το άθροισμα των γραμμών και για 0 το άθροισμα των στηλών

In [ ]:
matrix = np.array([[5, 10, 15], [20, 25, 30],[35, 40, 45]])
matrix.sum(axis=1)

In [ ]:
vector.mean()

In [ ]:
matrix.mean(axis=1)

### Άσκηση

Να βρεθεί το σύνολο των γεννήσεων τη χρονιά 1996 και μήνα Νοέμβριο